// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateEscrowPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      uint32                 `protobuf:"varint,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateEscrowPaymentRequest) Reset() {
	*x = InitiateEscrowPaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateEscrowPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateEscrowPaymentRequest) ProtoMessage() {}

func (x *InitiateEscrowPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateEscrowPaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiateEscrowPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateEscrowPaymentRequest) GetEscrowId() uint32 {
	if x != nil {
		return x.EscrowId
	}
	return 0
}

func (x *InitiateEscrowPaymentRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateEscrowPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiateEscrowPaymentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InitiateEscrowPaymentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl     string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	TransactionRef string                 `protobuf:"bytes,2,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateEscrowPaymentResponse) Reset() {
	*x = InitiateEscrowPaymentResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateEscrowPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateEscrowPaymentResponse) ProtoMessage() {}

func (x *InitiateEscrowPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateEscrowPaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiateEscrowPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateEscrowPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *InitiateEscrowPaymentResponse) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

type VerifyPaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionRef string                 `protobuf:"bytes,1,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPaymentRequest) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

type VerifyPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentResponse) Reset() {
	*x = VerifyPaymentResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentResponse) ProtoMessage() {}

func (x *VerifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/payment/v1/payment.proto\x12\n" +
	"payment.v1\"\x85\x01\n" +
	"\x1cInitiateEscrowPaymentRequest\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\rR\bescrowId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"i\n" +
	"\x1dInitiateEscrowPaymentResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\x12'\n" +
	"\x0ftransaction_ref\x18\x02 \x01(\tR\x0etransactionRef\"?\n" +
	"\x14VerifyPaymentRequest\x12'\n" +
	"\x0ftransaction_ref\x18\x01 \x01(\tR\x0etransactionRef\"1\n" +
	"\x15VerifyPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd4\x01\n" +
	"\x0ePaymentService\x12l\n" +
	"\x15InitiateEscrowPayment\x12(.payment.v1.InitiateEscrowPaymentRequest\x1a).payment.v1.InitiateEscrowPaymentResponse\x12T\n" +
	"\rVerifyPayment\x12 .payment.v1.VerifyPaymentRequest\x1a!.payment.v1.VerifyPaymentResponseB\x14Z\x12./proto/payment/v1b\x06proto3"

var (
	file_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_proto_rawDescData
}

var file_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_payment_v1_payment_proto_goTypes = []any{
	(*InitiateEscrowPaymentRequest)(nil),  // 0: payment.v1.InitiateEscrowPaymentRequest
	(*InitiateEscrowPaymentResponse)(nil), // 1: payment.v1.InitiateEscrowPaymentResponse
	(*VerifyPaymentRequest)(nil),          // 2: payment.v1.VerifyPaymentRequest
	(*VerifyPaymentResponse)(nil),         // 3: payment.v1.VerifyPaymentResponse
}
var file_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.InitiateEscrowPayment:input_type -> payment.v1.InitiateEscrowPaymentRequest
	2, // 1: payment.v1.PaymentService.VerifyPayment:input_type -> payment.v1.VerifyPaymentRequest
	1, // 2: payment.v1.PaymentService.InitiateEscrowPayment:output_type -> payment.v1.InitiateEscrowPaymentResponse
	3, // 3: payment.v1.PaymentService.VerifyPayment:output_type -> payment.v1.VerifyPaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_proto_init() }
func file_proto_payment_v1_payment_proto_init() {
	if File_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_proto = out.File
	file_proto_payment_v1_payment_proto_goTypes = nil
	file_proto_payment_v1_payment_proto_depIdxs = nil
}
